sudo: required
services:
  - docker

before_install:
  - docker build -t nsovomashaba/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nsovomashaba/react-test npm run test -- --coverage 

after_success:
  - docker build -t nsovomashaba/multi-client ./client
  - docker build -t nsovomashaba/multi-nginx ./nginx
  - docker build -t nsovomashaba/multi-server ./server
  - docker build -t nsovomashaba/multi-worker ./worker

#take images and push them to docker hub
#use docker login command to 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# pushing images to dockerhub
  - docker push nsovomashaba/multi-client
  - docker push nsovomashaba/multi-nginx
  - docker push nsovomashaba/multi-server
  - docker push nsovomashaba/multi-worker

deploy:
  provider: elasticbeanstalk
   #aws region where the container is located, DockerReact-env.eba-8xqfk7i4.us-east-2.elasticbeanstalk.com
  region: us-east-2
  app: multi-docker              
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-679308915134
  bucket_path: docker-multi
  #only attempt to deploy when we push code to master
  on: 
    branch: master
     #generate API keys on aws - use travic CI to store the key do not store this in the file 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    #secure : $AWS_SECRET_KEY is used only when we have encrypted our keys and etc see: https://docs.travis-ci.com/user/environment-variables/ and https://docs.travis-ci.com/user/encryption-keys#usage
  skip_cleanup: true